version: "3"

services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

